cmd_vel:
  topic: "/cmd_vel"
  msg_type: "geometry_msgs/Twist"
  buffer_size: 200
  update_rate: 10  # Hz

  filters:
    velocity:
      type: "moving_average"
      window_size: 5

  limits:
    max_linear_speed: 1.0   # m/s
    max_angular_speed: 1.5  # rad/s
    max_linear_acc: 1.0     # m/s²
    max_angular_acc: 2.0    # rad/s²

  plots:
    linear_velocity:
      title: "Linear Velocity"
      x_label: "Time (s)"
      y_label: "m/s"
      curves:
        - name: "x"
          color: "#1f77b4"
        - name: "y"
          color: "#ff7f0e"
        - name: "z"
          color: "#2ca02c"

    angular_velocity:
      title: "Angular Velocity"
      x_label: "Time (s)"
      y_label: "rad/s"
      curves:
        - name: "x"
          color: "#1f77b4"
        - name: "y"
          color: "#ff7f0e"
        - name: "z"
          color: "#2ca02c"

  motion_analysis:
    enabled: true
    metrics:
      - name: "acceleration"
        type: "derivative"
        input: "velocity"
      - name: "jerk"
        type: "derivative"
        input: "acceleration"
      - name: "smoothness"
        type: "rmse"
        input: "jerk"