# 高性能配置
ui:
  theme: dark # 降低GPU负载
  refresh_rate: 30
  use_opengl: true

buffer:
  size: 1000
  use_threading: true
  batch_update: true

optimization:
  enable_downsampling: true
  clip_to_view: true
  antialiasing: true
  use_cached_data: true

processing:
  parallel_processing: true
  batch_size: 100
  prefetch_size: 2
