performance:
  cpu:
    warning_threshold: 70
    critical_threshold: 90

  memory:
    warning_threshold: 70
    critical_threshold: 90
    max_buffer_size: 1000

  disk:
    warning_threshold: 70
    critical_threshold: 90
    min_free_space: 1000  # MB

  network:
    max_bandwidth: 100  # MB/s
    warning_latency: 100  # ms
    critical_latency: 500  # ms

  ros:
    max_queue_size: 100
    max_reconnect_attempts: 3
    message_timeout: 1.0

  optimization:
    enable_compression: true
    compression_level: 6
    enable_caching: true
    cache_size: 100
    enable_batch_processing: true
    batch_size: 10